# Generated by Django 3.0.8 on 2020-07-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status_post', 'verbose_name_plural': 'status posts'},
        ),
    ]
